---
title: "AML datasets"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>",
    warning = FALSE,
    message = FALSE
)
```

## Mouse datasets 
Note: Validation mice also available via Haemdata/Ondrive. See [X]() for more details.

First, we need to setup the pin-board and download the mouse datasets. 

```{r setup}
library(haemdata)
use_pinboard("onedrive")

all_mice <- get_pin("mmu_mrna_all_mice_GENCODEm28_HLT_qc.rds")
metadata_mmu <- get_pin("metadata_mmu.csv")
```

::: {.panel-tabset}

### 2016 mice
```{r}
se <- subset(all_mice,
    select = grepl("2016", SummarizedExperiment::colData(all_mice)$batch)
)

pca <- pca_se(se)
```

```{r}
pca$biplot
pca$pairs_plot
```

```{r fig.height=9, fig.width=8}
pca$correlation_plot
```

```{r}
plot_transgenes_se(se)
```

```{r }
metadata_mmu |>
plot_cohort_survival("AML.mRNA.2016")
```

### 2018 mice
```{r}
se <- subset(all_mice,
    select = grepl("AML.mRNA.2018.all_samples", SummarizedExperiment::colData(all_mice)$cohort)
)

pca <- pca_se(se)
```

```{r }
pca$biplot
pca$pairs_plot
```
```{r fig.height=9, fig.width=8}
pca$correlation_plot
```

```{r, eval = FALSE }
plot_transgenes_se(se)
```

```{r }
metadata_mmu |>
plot_cohort_survival("AML.mRNA.2018")
```

### Radiation mice
```{r}
se <- subset(all_mice,
    select = grepl("AML.mRNA.2020", SummarizedExperiment::colData(all_mice)$cohort)
)
se <- subset(se,
    select = grepl("PBMC", SummarizedExperiment::colData(se)$tissue)
)

pca <- pca_se(se)
```

```{r }
pca$biplot
pca$pairs_plot
```

```{r fig.height=9, fig.width=8}
pca$correlation_plot
```

```{r }
plot_transgenes_se(se)
```

```{r }
metadata_mmu |>
plot_cohort_survival("AML.mRNA.2020")
```

### Chemo mice
```{r}
se <- subset(all_mice,
    select = grepl("RxGroup", SummarizedExperiment::colData(all_mice)$cohort)
)

pca <- pca_se(se)
```

```{r }
pca$biplot
pca$pairs_plot
```

```{r fig.height=9, fig.width=8}
pca$correlation_plot
```

```{r eval = FALSE }
plot_transgenes_se(se)
```

```{r }
metadata_mmu |>
plot_cohort_survival("RxGroup")
```

### scRNAseq mice 2022
```{r}
se <- subset(all_mice,
    select = grepl("AML.scRNAseq.2022", SummarizedExperiment::colData(all_mice)$cohort)
)

pca <- pca_se(se)
```

```{r }
pca$biplot
pca$pairs_plot
```

```{r fig.height=9, fig.width=8}
pca$correlation_plot
```

```{r eval = FALSE }
plot_transgenes_se(se)
```

### Bone marrow
```{r}
se <- subset(all_mice,
    select = ("BM" == SummarizedExperiment::colData(all_mice)$tissue)
)
se <- subset(se,
    select = grepl("AML", SummarizedExperiment::colData(se)$cohort)
)

pca <- pca_se(se)
```

```{r }
pca$biplot
pca$pairs_plot
```

```{r fig.height=9, fig.width=8}
pca$correlation_plot
```

```{r eval = FALSE }
plot_transgenes_se(se)
```
 
:::


:::
