#'  SummarisedExperiment of 226 samples
#'
#' A `SummarisedExperiment` generated by `cbind`ing the `cml_mrna_2021` and `cml_mrna_2022` datasets.
#' After QC, the following samples were removed:
#' `c("F545.7", "X490.17")`
#'
#' The original datasets were prepared using the nf-core/rnaseq v3.5 pipeline with Salmon
#' and tximport. See the pipeline [documentation](https://nf-co.re/rnaseq/3.5/output#pseudo-alignment-and-quantification)
#' for details. The [reference](../articles/genomes.html)
#' is GRCm38 using Ensembl annotation v81 (July 2015) with human leukemic transcripts (MYH11, BCR & ABL1).
#'
#' Only the Salmon *[transcript length bias corrected](https://nf-co.re/rnaseq/3.5/output#pseudo-alignment-and-quantification)* counts are available in this package;
#' for other datasets, see the full pipeline output for [2021](http://cgt.coh.org/MHO/CML.mRNA.2021/results/rnaseq3.5.GRCm38.HLT/)
#' and [2022](http://cgt.coh.org/MHO/CML.mRNA.2021/results/rnaseq3.5.GRCm38.HLT/).
#'
#' @format A `SummarisedExperiment` object containing 226 samples.
#' \describe{
#'   \item{counts}{`mat` Salmon *transcript length bias corrected* gene counts}
#'   \item{abundance}{`mat` Salmon *transcript length bias corrected* TPM}
#' }
#' @source [merge_mrna()]
#' @name cml_mrna_GRCm38_HLT
#' @docType data
#' @keywords cml mrna 2021 2022
#' @usage data(cml_mrna_GRCm38_HLT)
NULL
